### ISSUE TITLE
"Share" popup: Share to Confluence

### ISSUE THREAD

**Issue by MrCoder** [ZenUml/web-sequence#556]
When the user clicks the "Share" button, a dialog should pop up (near to the button). On the pop up dialog, two elements must be included:

1. A link to the page that renders the diagram with OG attributes (a separate task);
2. An instruction on how to paste the link on to a Confluence page; explain anyone with this URL can view this diagram;
3. An animation shows how to paste the link on to a Confluence page;

A proposed layout:

![Image](https://github.com/ZenUml/web-sequence/assets/169417/6211e44c-082a-46e2-9923-810a2389e98c)

**Comment by MrCoder** [comment]
Dependencies:
#557

**Comment by dontry** [comment]
https://github.com/ZenUml/web-app-laravel/pull/151 new card style

<img width="786" alt="image" src="https://github.com/ZenUml/web-app-laravel/assets/125171539/5eb2aebe-af64-4ba2-a024-270b5a07a454">
