### ISSUE TITLE
Generated sharable link

### ISSUE THREAD

**Issue by MrCoder** [ZenUml/web-sequence#557]

**Comment by MrCoder** [comment]
- 这个链接应该是应该永久链接（除非被吊销），即如果对应的图发生了变化，同一个链接应当指向变化了内容。
- 这个链接应该在点击「Share」的时候请求Function并进一步请求New Web App生成。New Web App检查自己是否已经有了对应的Diagram，如果已经有了就直接返回；如果没有就生成后返回。（请求评论）

**Comment by MrCoder** [comment]
一个小细节，这个链接里面要不要加点「盐」？
一般来说大部分平台对于同一个链接是会缓存OG image的，我怀疑他们也会缓存description。如果我们加了盐，至少可以让用户使用同一个图的不同版本的时候强制平台重新获取最新的元数据。

**Comment by whimet** [comment]
可以用DSL的md5做“盐”。

**Comment by whimet** [comment]
PR: https://github.com/ZenUml/web-sequence/pull/560

**Comment by whimet** [comment]
Share link example so far: http://sequence-diagram.zenuml.com/share/37262115-bfde-4217-998f-ea4ca22243c6:fBdLQHlYbdJdR5HNDKGd8jZC3cWbpTYT?v=243e8824e21f73a77a4f3d7b35db34d3

**Comment by whimet** [comment]
https://seq-diagram.docs-68d.pages.dev/sequence-diagram/share/4a20bcb1-4b2a-4726-9d45-7e7e9db7de8a:ZpzcJzwlYIkL4YinwTyGQgbwWktkzv37?v=243e8824e21f73a77a4f3d7b35db34d3 works.
