### ISSUE TITLE
[Bug] Web App (https://app.zenuml.com) always load the same diagram instead of previous diagram

### ISSUE THREAD

**Issue by MrCoder** [ZenUml/web-sequence#623]
Reproduce steps:
1. Open https://app.zenuml.com
2. Login if you have not
3. Create a diagram, if it did not open a diagram automatically
4. Save this diagram
5. Create a new diagram
6. Save the new diagram
7. Refresh the page.

Expected result:
It should load the diagram created on step 5.

Actual result:
It loads the diagram created on step 3.

**Comment by whimet** [comment]
https://github.com/ZenUml/web-sequence/pull/626
