### ISSUE TITLE
Can't create share link even file saved

### ISSUE THREAD

**Issue by danshuitaihejie** [ZenUml/web-sequence#629]
未登录状态下进入 https://app.zenuml.com 后，会打开一个默认的diagram，点share link，提示需要保存，登陆后，编辑该diagram，保存后再create share link，依然显示需要保存。

![image](https://github.com/ZenUml/web-sequence/assets/48118719/916bc887-1adf-4376-8037-8d5491307ae3)

**Comment by MrCoder** [comment]
Root cause 应该是https://github.com/ZenUml/web-app-laravel/issues/193。我把LaraSite回滚了。你再试一下？

**Comment by danshuitaihejie** [comment]
> Root cause 应该是[ZenUml/web-app-laravel#193](https://github.com/ZenUml/web-app-laravel/issues/193) 。我把LaraSite回滚了。你再试一下？

回滚后现在ok了。
