### ISSUE TITLE
评估和确认是否更换用户支付服务 Paddle / Lemonsqueezy

### ISSUE THREAD

**Issue by iamshaynez** [ZenUml/web-sequence#653]
只为了评估，评估后如果需要修改并产生开发工作，另外建卡。

需求：

- 支持按月，按年订阅，分别定价
- 支持促销，如 coupon 等
- 支持早鸟价，如部分用户锁定一个不同的长期订阅价格
- 支持兑换码，如激活若干时间的订阅（3 个月）
- 更低费率？

以上不是必须的需求，只是罗列评估要点。

**Comment by MrCoder** [comment]
暂时不切换。如果付费用户数量达到一定数量，比如20+再考虑这个问题。
